---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner

images:
  base_image:
    name: registry.access.redhat.com/ubi8/python-39:latest

additional_build_files:
  - src: pyproject.toml
    dest: app
  - src: src
    dest: app/src

additional_build_steps:
  append_final:
    - COPY _build/app .
    - RUN pip install -e .

options:
  container_init:
    cmd: "uvicorn network_visualization_app.app:app --host 0.0.0.0 --port 8000"
